// ignore_for_file: non_constant_identifier_names

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `user_model.dart` with the code generated by Freezed
part 'leaderboard_model.freezed.dart';
// optional: Since our UserModel class is serializable, we must add this line.
// But if UserModel was not serializable, we could skip it.
part 'leaderboard_model.g.dart';

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter
    implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class LeaderboardModel with _$LeaderboardModel {
  const factory LeaderboardModel({
    required double eTask_earned,
    @TimestampConverter() DateTime? lastUpdated,
    required int tasks_completed,
    required String user_id,
    required double xrp_earned,
  }) = _LeaderboardModel;

  factory LeaderboardModel.fromJson(Map<String, Object?> json) =>
      _$LeaderboardModelFromJson(json);

  factory LeaderboardModel.defaultEvent() {
    return const LeaderboardModel(
        eTask_earned: 0, user_id: '', xrp_earned: 0, tasks_completed: 0);
  }
}
