runtime: python39

service: taskcoin

env_variables:
  # Replace <YOUR_DATABASE_URL> with your actual database URL
  DATABASE_URL: <YOUR_DATABASE_URL>

# The container listens to incoming requests on port 8080.
# This should match the port specified in the Flask app's Dockerfile.
port: 8080

# Set the container image to be built and deployed
containers:
  - name: app
    image: gcr.io/<task-coin-384722>/<taskcoin>
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - containerPort: 8080
