version: '3.8'

services:
  mono_service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CORS_ORIGINS=http://localhost:3000,http://localhost:19006
      - GOOGLE_APPLICATION_CREDENTIALS=/app/src/config/service_accounts/task-coin-384722-4adf1998dd08.json
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./src/config/service_accounts:/app/src/config/service_accounts
