import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `user_model.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our UserModel class is serializable, we must add this line.
// But if UserModel was not serializable, we could skip it.
part 'user_model.g.dart';

///Model for cloud data
class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class UserModel with _$UserModel {
  const factory UserModel({
     String? displayName,
     String? email,
     String? imageUrl,
    required String uid,
    @TimestampConverter() DateTime?  dateCreated,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) =>
      _$UserModelFromJson(json);
}

UserModel defaultUserModel = UserModel(
    displayName: 'displayName',
    email: 'user@user.com',
    imageUrl: 'photoURL',
    uid: 'uid',
    dateCreated: DateTime.now());
    
@freezed
class CurrentUserModel with _$CurrentUserModel {
  const factory CurrentUserModel({
     String? displayName,
     String? email,
     String? imageUrl,
     String? publicAddress,
    required String uid,
  }) = _CurrentUserModel;

  factory CurrentUserModel.fromJson(Map<String, Object?> json) =>
      _$CurrentUserModelFromJson(json);
}

CurrentUserModel defaultUserModel2 = const CurrentUserModel(
    displayName: 'displayName',
    email: 'user@user.com',
    imageUrl: 'photoURL',
    uid: 'uid',
    publicAddress: 'address');